version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: bank-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: bank-redis
    ports:
      - '6379:6379'

  migrate:
    image: migrate/migrate
    container_name: bank-migrations
    depends_on:
      db:
        condition: service_started
    entrypoint:
      [
        'migrate',
        '-path',
        '/migrations',
        '-database',
        'mysql://root:root@tcp(db:3306)/bank',
        'up',
      ]
    volumes:
      - ./migrations:/migrations

  app:
    build: .
    container_name: bank-api
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started
      redis:
        condition: service_started
